language: node_js
node_js:
  - "node"
script:
  - npm run build
deploy:
  provider: pages
  local-dir: public
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
